repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: no-commit-to-branch

- repo: https://github.com/pycqa/flake8
  rev: 7.0.0
  hooks:
    - id: flake8
      args: ['--exclude=docs/*', '--ignore=E501,W503,E203']

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort
      args: ['--check-only', '--diff']
      additional_dependencies: ['toml']

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
    - id: black
