language: python
cache: pip

matrix:
  include:
    - python: 3.6
      dist: xenial
      env: TOX_ENV=py36
    - python: 3.7
      dist: xenial
      env: TOX_ENV="py37,lint"

before_install:
  - pip install --upgrade pip

install:
  - pip install tox poetry==1.0.0b2

script:
  - tox -e $TOX_ENV
